POKEMON_BY_INDEX = [
    "",
    "Rhydon",
    "Kangaskhan",
    "Nidoran♂",
    "Clefairy",
    "Spearow",
    "Voltorb",
    "Nidoking",
    "Slowbro",
    "Ivysaur",
    "Exeggutor",
    "Lickitung",
    "Exeggcute",
    "Grimer",
    "Gengar",
    "Nidoran♀",
    "Nidoqueen",
    "Cubone", 
    "Rhyhorn",
    "Lapras",
    "Arcanine",
    "Mew",
    "Gyarados",
    "Shellder",
    "Tentacool",
    "Gastly",
    "Scyther",
    "Staryu",
    "Blastoise",
    "Pinsir",
    "Tangela",
    "MissingNo",
    "MissingNo",
    "Growlithe",
    "Onix",
    "Fearow",
    "Pidgey",
    "Slowpoke",
    "Kadabra",
    "Graveler",	
    "Chansey",
    "Machoke",
    "Mr. Mime",
    "Hitmonlee",
    "Hitmonchan",
    "Arbok",
    "Parasect",
    "Psyduck",
    "Drowzee",
    "Golem",
    "MissingNo.  (Balloonda)",
    "Magmar",
    "MissingNo.  (Buu)",
    "Electabuzz",
    "Magneton",
    "Koffing",
    "MissingNo.  (Deer)",
    "Mankey",
    "Seel",
    "Diglett",
    "Tauros",
    "MissingNo.  (Elephant Pokémon)",
    "MissingNo.  (Crocky)",
    "MissingNo.  (Squid Pokémon 1)",
    "Farfetch'd",
    "Venonat",
    "Dragonite",
    "MissingNo.  (Cactus)",
    "MissingNo.  (Jaggu)",
    "MissingNo.  (Zubat pre-evo)",
    "Doduo",
    "Poliwag",
    "Jynx",
    "Moltres",
    "Articuno",
    "Zapdos",
    "Ditto",
    "Meowth",
    "Krabby",
    "MissingNo.  (Fish Pokémon 1)",
    "MissingNo.  (Fish Pokémon 2)",
    "MissingNo.  (Vulpix pre-evo)",
    "Vulpix",
    "Ninetales",
    "Pikachu",
    "Raichu",
    "MissingNo.  (Frog-like Pokémon 1)",
    "MissingNo.  (Frog-like Pokémon 2)",
    "Dratini",
    "Dragonair",
    "Kabuto",
    "Kabutops",
    "Horsea",
    "Seadra",
    "MissingNo.  (Lizard Pokémon 2)",
    "MissingNo.  (Lizard Pokémon 3)",
    "Sandshrew",
    "Sandslash",
    "Omanyte",
    "Omastar",
    "Jigglypuff",
    "Wigglytuff",
    "Eevee",
    "Flareon",
    "Jolteon",
    "Vaporeon",
    "Machop",
    "Zubat",
    "Ekans",
    "Paras",
    "Poliwhirl",
    "Poliwrath",
    "Weedle",
    "Kakuna",
    "Beedrill",
    "MissingNo.  [Unknown]",
    "Dodrio",
    "Primeape",
    "Dugtrio",
    "Venomoth",
    "Dewgong",
    "MissingNo.  [Unknown]",
    "MissingNo.  (Squid Pokémon 2)",
    "Caterpie",
    "Metapod",
    "Butterfree",
    "Machamp",
    "MissingNo.  (Golduck mid-evo)",
    "Golduck",
    "Hypno",
    "Golbat",
    "Mewtwo",
    "Snorlax",
    "Magikarp",
    "MissingNo.  (Meowth pre-evo)",
    "MissingNo.  [Unknown]",
    "Muk",
    "MissingNo.  (Gyaoon pre-evo)",
    "Kingler",
    "Cloyster",
    "MissingNo.  (Magneton-like Pokémon)",
    "Electrode",
    "Clefable",
    "Weezing",
    "Persian",
    "Marowak",
    "MissingNo.  (Marowak evo)",
    "Haunter",
    "Abra",
    "Alakazam",
    "Pidgeotto",
    "Pidgeot",
    "Starmie",
    "Bulbasaur",
    "Venusaur",
    "Tentacruel",
    "MissingNo.  (Goldeen pre-evo)",
    "Goldeen",
    "Seaking",
    "MissingNo.  (Kotora)",
    "MissingNo.  (Raitora)",
    "MissingNo.  (Raitora evo)",
    "MissingNo.  (Ponyta pre-evo)",
    "Ponyta",
    "Rapidash",
    "Rattata",
    "Raticate",
    "Nidorino",
    "Nidorina",
    "Geodude",
    "Porygon",
    "Aerodactyl",
    "MissingNo.  (Blastoise-like Pokémon)",
    "Magnemite",
    "MissingNo.  (Lizard Pokémon 1)",
    "MissingNo.  (Gorochu)",
    "Charmander",
    "Squirtle",
    "Charmeleon",
    "Wartortle",
    "Charizard",
    "MissingNo.  (Original Wartortle evo)",
    "MissingNo.  (Kabutops Fossil)",
    "MissingNo.  (Aerodactyl Fossil)",
    "MissingNo.  (Pokémon Tower Ghost)",
    "Oddish",
    "Gloom",
    "Vileplume",
    "Bellsprout",
    "Weepinbell",
    "Victreebel"
]

POKEMON_IN_THE_ACTUAL_GODDAMN_CORRECT_ORDER = [
    "Bulbasaur",
"Ivysaur",
"Venusaur",
"Charmander",
"Charmeleon",
"Charizard",
"Squirtle",
"Wartortle",
"Blastoise",
"Caterpie",
"Metapod",
"Butterfree",
"Weedle",
"Kakuna",
"Beedrill",
"Pidgey",
"Pidgeotto",
"Pidgeot",
"Rattata",
"Raticate",
"Spearow",
"Fearow",
"Ekans",
"Arbok",
"Pikachu",
"Raichu",
"Sandshrew",
"Sandslash",
"Nidoran♀",
"Nidorina",
"Nidoqueen",
"Nidoran♂",
"Nidorino",
"Nidoking",
"Clefairy",
"Clefable",
"Vulpix",
"Ninetales",
"Jigglypuff",
"Wigglytuff",
"Zubat",
"Golbat",
"Oddish",
"Gloom",
"Vileplume",
"Paras",
"Parasect",
"Venonat",
"Venomoth",
"Diglett",
"Dugtrio",
"Meowth",
"Persian",
"Psyduck",
"Golduck",
"Mankey",
"Primeape",
"Growlithe",
"Arcanine",
"Poliwag",
"Poliwhirl",
"Poliwrath",
"Abra",
"Kadabra",
"Alakazam",
"Machop",
"Machoke",
"Machamp",
"Bellsprout",
"Weepinbell",
"Victreebel",
"Tentacool",
"Tentacruel",
"Geodude",
"Graveler",
"Golem",
"Ponyta",
"Rapidash",
"Slowpoke",
"Slowbro",
"Magnemite",
"Magneton",
"Farfetch'd",
"Doduo",
"Dodrio",
"Seel",
"Dewgong",
"Grimer",
"Muk",
"Shellder",
"Cloyster",
"Gastly",
"Haunter",
"Gengar",
"Onix",
"Drowzee",
"Hypno",
"Krabby",
"Kingler",
"Voltorb",
"Electrode",
"Exeggcute",
"Exeggutor",
"Cubone",
"Marowak",
"Hitmonlee",
"Hitmonchan",
"Lickitung",
"Koffing",
"Weezing",
"Rhyhorn",
"Rhydon",
"Chansey",
"Tangela",
"Kangaskhan",
"Horsea",
"Seadra",
"Goldeen",
"Seaking",
"Staryu",
"Starmie",
"Mr. Mime",
"Scyther",
"Jynx",
"Electabuzz",
"Magmar",
"Pinsir",
"Tauros",
"Magikarp",
"Gyarados",
"Lapras",
"Ditto",
"Eevee",
"Vaporeon",
"Jolteon",
"Flareon",
"Porygon",
"Omanyte",
"Omastar",
"Kabuto",
"Kabutops",
"Aerodactyl",
"Snorlax",
"Articuno",
"Zapdos",
"Moltres",
"Dratini",
"Dragonair",
"Dragonite",
"Mewtwo",
"Mew",
]


def species_id_for(pokemon):
    return POKEMON_BY_INDEX.index(pokemon) 


TRADE_EVOLUTIONS = {
    species_id_for("Machoke"): species_id_for("Machamp"),
    species_id_for("Graveler"): species_id_for("Golem"),
    species_id_for("Haunter"): species_id_for("Gengar"),
    species_id_for("Kadabra"): species_id_for("Alakazam")
}

def stupid_index_to_correct_index(index):
    return POKEMON_IN_THE_ACTUAL_GODDAMN_CORRECT_ORDER.index(POKEMON_BY_INDEX[index])